import React from 'react'
import HtmlHead from '../HtmlHead'

const PrivacPolicy = () => {
  return (

    <div>
       <HtmlHead
		title='Excelsior | Online Education Platform | Privacy Policy'
		desc='Best online training institute in Delhi NCR and Bengaluru for Data Science '
        kw='Best Data Science Course, Machine Learning Courses, Best online Course in Delhi NCR, Best online course in Bengaluru, Specialization in Data Science for Finance, Specialization in Data Science for IT, Finance Data Science, Data Science for IT, Deep Learning, Python programming, Machine Learning, Data Analytics, Financial Analytics '
			/>
        <div className='container mt-4'>
    <h1 className='Banner_Heading'>EXCELSIOR</h1>
    <h3 className='mb-4 '>Privacy Policy</h3>
    <p>Excelsior respects your privacy and is determined to safeguard your personal information shared with us. We're a three-dimensional organization that has been created as a one-stop solution platform for investigating, lengthening, and farming. In this document of privacy policy, we assess and secure your personal details when you read our site (https://getexcelsior.com/) or interpretate us through a telephone. Please note that whenever you go through "you" on Excelsior's website, it refers to as "user", "your", or "you". If you go through the word “Platform”, it indicates “Excelsior”, our extensive learning division.
<br/>Since we value our users' privacy, we try to protect their information by implementing the most secure measures that are currently used. For example, we encrypt all of our users' credit card information so that someone else can't decode it and then use it for purposes unrelated to what the user intended. This is just a small example of how seriously we take consumers' security. If you have any questions regarding our Secure Socket Layer (SSL) solution or you do not agree with one of our policies described in the Security Section, please contact us at info@getexcelsior.com . We will reply to your inquiry as quickly as possible.
<br/> All the privacy policies explained in this important document adhere only to the part of the platform, products and services provided by Excelsior, and we are not liable for any practises performed by people, organizations, institutions, and websites that Excelsior does not operate, manage, or employ. Our aim is to aid you with the successful use of our website i.e. https://getexcelsior.com/ and to safeguard your set of crucial information you share with us.
<br/>Please note that by making use of our platform to submit any PII (Personally Identifiable Information) to us, you abide by our collection, usage, disclosure and retainment of your details (comprised of but not limited to PII) in accord with this document of privacy policy and terms of use, and as required and permitted by the law. Excelsior reserves all the rights to share your details collected hereunder with its affiliates. In the matter of sale or sharing of all or a portion of business assets, your personal information is one of the business assets that may get shared as part of the transaction. If you do not agree with our privacy policies, it is requested not to provide any of your personally identifiable information to us on call or on our website. Note that if you withdraw your consent or deny providing any of your crucial personal details, we might not be able to offer you any of our services and products that are provided on our website. </p>
<h2 className='custom-text-primary mt-3'>OTHER INFORMATION</h2>
<p>Other forms of information that we may collect from you or about you are as follows:
<li>Information about your interactions with customer service and maintenance interactions with us</li>
<li>User-generated content you upload or post to public forums through the Platform</li>
<li>Information needed in order to comply with any procedures, laws, and regulations which apply to us where it is necessary for our legitimate interests or the legitimate interests of others</li>
<li>Recordings of calls with students or users showing interest in our programs</li>
<li>Any other information you choose to directly provide to us in connection with your use of the Platform and Programs </li></p>
<h2 className='custom-text-primary mt-3'>THIRD-PARTY SERVICE PROVIDERS</h2>
<p>Excelsior may use the information we collect to provide you with information relating to our Programs and/or other services we may offer. This includes responding to your questions or interest shown in our Programs, sending you updates about the Program and/or other events, platform maintenance or new services provided by Excelsior, and connecting with you via email, SMS, phone call or any other medium. We also may send you communications relating to us and/or third parties through these mediums. You consent to this use of your personal information by Excelsior as described in this Privacy Policy, which you agree to deregister from if required by the National Do Not Call Registry."
<br/>We use your information for administration purposes, including but not limited to tracking attendance, progress and completion of a Program. As part of our administration and management of the Program, we will use personally identifiable information to administer exams, projects, and other assessments for the Program. For example, as part of an exam, we may use information collected from you in order to verify your identity or to monitor your performance during the exam to confirm that you are abiding by the applicable testing rules or requirements.
<br/>We may use your Personally Identifiable Information to provide you with the services you requested. We may also use this information to verify your identity, as well as for quality control purposes. For example, we may archive this information and/or use it for future communications with you. For example, Excelsior may make available to you chat room services that allow you to communicate with Excelsior’s staff members or your peers in the same cohort. We will share your Personally Identifiable Information to provide these services to you. In another example, Excelsior’s staff members may create groups on WhatsApp (or similar service providers) with other students and make you a member of such a group. These groups may be used to provide services in conjunction with the Programs, including, but not limited to, updates related to the Programs, details of potential employers, etc.
<br/>Please be aware that the information disclosed on a third-party service provider’s platform will be dependent and subject to such third-party’s privacy policies and/or on your settings regarding what information you have consented to share with them. Excelsior and/or its associates shall have no liability in this regard whatsoever.
<br/>Excelsior may use certain companies to enable you to create a membership account through which you can participate in digital wallets, payment services or rewards programs. If you elect to do so, we will provide your information to such companies in accordance with the terms of their respective privacy policies and as necessary for them to make their programs work for you. We are not responsible for the privacy practices of the companies sponsoring these membership programs, and we suggest that you review the individual privacy policies of each company with whom you establish a membership account. Information may be archived by us or our providers. We may archive Personally Identifiable Information other than billing information and/or use it for future communications with you.
"<br/>Excelsior may use and share your information to improve its services and offerings. For example, we, through our service providers (like auditors or surveyors), may approach you to understand the impact of our Programs on your careers. For this purpose, we may connect with you via a phone call, email you questionnaires, or request you to attend workshops.

To the extent any Personally Identifiable Information collected by us contains images of you, you grant Excelsior a limited, non-exclusive right to use, reproduce, distribute, or prepare derivative works of or publicly display such images and/or your likeness in relation to the Program or for marketing purposes. We may use your photograph along with employer information, transition information, designation change, etc., for Ads/and or social media posts to highlight our learners’ achievements."
<br/>We use Non-Personal Information in aggregate form to build higher-quality, more useful services by performing statistical analysis of the collective characteristics and behaviour of our Users and by measuring demographics and interests regarding specific areas of our Platform.</p>
<h2 className='custom-text-primary mt-3'>SHARING YOUR INFORMATION</h2>
<p>In addition to the examples provided above, we will share your information in the following manner:
<br/> <b>Educational Partners</b>
<br/>We may share the information that we collect from you with the particular educational partner that developed or offered the program you are taking; the instructors who taught, managed, or oversaw the program; external reviewers who will grade your performance; or mentors who will support students. For example, if you are taking a program through a university, we may share personally identifiable information about you and your performance with the university to report on your progress in the program and to enable them to issue a certificate to you on completion of the program. Information shared with our partners will be subject to those companies' privacy policies and procedures. Also, we may archive this information and use it for communications with you in future.
<br/> <b>Employers, Sponsors and Scholarship Providers</b>
<br/>If you are taking a Program sponsored by your employer or a sponsor, or if you have received a scholarship from a third-party scholarship provider, we may share your Personally Identifiable Information and grades, evaluations or progress in the Program with that entity. Such information may be shared at any time during the Program or afterward.
<br/> <b>Service Providers</b>
<br/>We provide access to or share your information with service providers who perform services on our behalf. These third parties have access to perform these services but are prohibited from using your information for other purposes. The third parties also may include billing, sales, marketing, test proctoring, couriers, mentoring, recruitment consulting, product content and features, advertising, analytics, research, customer service, data storage, security and credit facilities. Moreover, we may share certain Personally Identifiable Information and materials with third parties including, but not limited to such as those mentioned above in order to provide you services that you have requested or those provided by Excelsior in conjunction with the Programs.Also, we use certain third-party platforms to collect your information (such as Typeform or Google Forms), as a consequence of which, your information may be stored on their servers.
<br/> <b>Recruitment Services</b>
<br/>If you have opted for any of our recruitment services or if you participate in any of our recruitment activities, we will be sharing your information with recruiters and potential employers. For example, if you participate in a recruitment drive jointly organised by Excelsior’s Excelsior and a recruitment agency, we will share your information with the recruitment agency and with potential employers who wish to consider you for employment. In this case, such a recruitment agency or an employer may directly contact you to schedule interviews, etc. Please note that any information you share with the recruitment agency or employer will be governed by their policies.
<br/>As part of our career services, we offer a public profile which you can use to make your career details and information public on the Platform, including your progress in the Program. By electing to participate in this service, you acknowledge that any information or materials you include in your profile can be viewed by others accessing the Platform, including potential or existing employers, recruiters, peers, as well as others on the applicable third-party websites. You also acknowledge that the information shared may remain accessible on third-party websites and/or to those you have shared it with, in the event you make your profile private after having made it public and/or ceasing to share it. You also acknowledge that Excelsior has no control over the access of or use of information provided to third parties via this mode outside our website.
<br/> <b>Alumni Portal and Networking Services</b>
<br/>We may enter into an agreement with a company to provide internship-hunting activities—networking, social events, and the like. For this service, we share your name, email address, cohort information, and other info with that company in order to enable them to invite you to connect. If you agree to sign up for their services, please note that any information you provide will be governed by their policies. In certain cases, in order to facilitate communication between students and working professionals on chat forums such as WhatsApp and Facebook, we may share your contact details with other students and working professionals.
<br/> <b>Government and Regulatory Disclosure</b>
<br/>Excelsior may share your Information with various government authorities in response to court orders or other legal processes to establish or exercise our legal rights or to protect our property; to defend against legal claims; or as otherwise required by law. In such cases, we reserve the right to raise or waive any legal objection or right available to us. We may also share your information when we believe it is appropriate to investigate, prevent or take appropriate action regarding illegal or suspected illegal activities; to protect and defend the rights, property, or safety of Excelsior, the Platform, our users, customers, or others; and in connection with our Terms and other agreements.
<br/> <b>Associates and Business Transfers</b>
<br/>Excelsior may share your Personally Identifiable Information with any Associate. The term “Associate” includes, with respect to any person, any entity that is controlled by such person, or any entity that controls such person, or any entity that is under common control with such person, whether directly or indirectly, or, in the case of a natural person, any Relative (as such a term is defined in the Companies Act, 1956, and Companies Act, 2013, to the extent applicable) of such a person.
<br/>Excelsior may disclose and/or transfer your Personally Identifiable Information to an acquirer, assignee or other successor entity in connection with a sale, merger, or reorganisation of all or substantially all of the equity, business or assets of Excelsior to which your Personally Identifiable Information relates.
<br/> <b>Business Partners</b>
<br/>Excelsior (with your consent) may share information that can be used to directly contact you. We do this with third-party business partners like companies that may be offering products or services, or other opportunities that may be of interest to you. </p>

<h2 className='custom-text-primary mt-3'>PUBLIC DISCLOSURE OF INFORMATION</h2>
<p>Please note that any Personally Identifiable Information that is voluntarily displayed by you on the Platform may be used by third parties for unsolicited purposes. Excelsior shall not be liable for such unsolicited use by third parties of your Personally Identifiable Information.</p>
<h3 className='mt-3'><b>AGGREGATED DATA</b></h3>
<p>Aggregated Data means records that have been stripped of Personally Identifying Information and that have been manipulated or combined to provide generalised, anonymous information. Your identity and personal information are not available in Aggregated Data. We may combine your personal information on an anonymous basis with other information to generate Aggregated Data for internal and commercial use, and for sharing with affiliates, subsidiaries and business partners for planning and marketing purposes.</p>
<h3 className='mt-3 mb-2'><b>PROTECTION OF INFORMATION</b></h3>
<p><b>CONFIDENTIALITY AND SECURITY</b>
<br/>Excelsior is committed to protecting online privacy. In addition, we participate in cooperative database services. These services help us direct marketing efforts to appropriate purchasers and website visitors. Names and mailing addresses may be shared between participating parties in the co-operative database services.</p>
<p><b>NOTIFICATION OF CHANGES</b>
<br/>We may update this Privacy Policy at any time, and all revisions will be posted on the Platform so that you are aware of what information we collect, how we use it, and the circumstances under which we may disclose it. Unless stated otherwise, our current privacy policy applies to all information that Excelsior has about You or Your account, even if it was collected in the past.</p>
<p><b>YOUR EMAIL ADDRESS AND MOBILE NUMBER</b>
<br/>If you elect to receive emails or SMSs from us, we may store the mobile number or email address you provided. By providing an email address for our database, you can learn about special promotions and offers. If you change your mind about receiving these types of communications, you can easily change your preferences. To opt out of regular mail, email us at info@getexcelsior.in </p>
<p><b>THIRD-PARTY LINKS</b>
<br/>The Platform may contain links to third-party websites. Excelsior is not responsible for the privacy practices of such websites, and we advise you to read the privacy policies of each website that collects your information, including Personally Identifiable Information. If you decide to visit any of these linked sites, you do so entirely at your own risk. Any links to partner websites should be assumed to have been created by that website or organization and not by Excelsior, and Excelsior shall not be responsible for notifying you of any change in the name or location of any information on the Platform.</p>
<p><b>RETENTION OF PERSONALLY IDENTIFIABLE INFORMATION</b>
<br/>If you reside or are located in the European Union, we keep your Personally Identifiable Information for no longer than is necessary for the purposes for which the Personally Identifiable Information is processed. The length of time we retain Personally Identifiable Information depends on the purposes for which we collect and use it and/or as required by applicable laws.</p>
<p><b>SERVERS</b>
<br/>Our service providers store information about you on servers located in India, whereas our international service providers may store your personal information on servers located in other countries. By using our services, you consent to the storage of your information within India or such other countries. If you are using the services from outside India, please be aware that, by submitting your personal information and/or using our services, your data will be transferred to and stored in our servers in India or such other countries. The data protection and other laws of India and/or other countries might not be as comprehensive as those in your country. By submitting your personal data and/or using our services, you acknowledge the transfer, storage and processing of your information in and to India.
<br/>As described above, Excelsior may subcontract the processing of your data to, or otherwise share your data with, third parties. Such third-parties may include service providers or others in countries other than your country of residence, including India. These parties may provide services to you or perform transactions on your behalf and/or provide support services. By providing us with your information, you acknowledge any such transfer, storage or use.</p>
<p><b>COOKIES AND WEB BEACONS</b>
<br/>Our servers save data called "cookies" on your computer. Cookies record aspects of your visit to our Platform and let us track the pages you've visited, purchases you've made, and other activities while using our Platform. Web beacons are small graphic images linked to our servers that allow us to see how you browse the web, including use of our Platform.
<br/>We also use cookies and/or web beacons to help us determine the type of content and sites our users are linking to, their length of time visiting our platform, and their specific activity on our site. Cookies and web beacons help us serve you better and more efficiently, and personalise your experience on our site. By using these technologies, we do not collect personally identifiable information.
<br/>We may allow third-party companies, including advertising companies (such as Facebook, Google, Twitter, Quora and Bing) to place cookies on our website. These cookies enable such companies to track your activity across various sites where they display Ads and record your activities, so they can show Ads that they consider relevant to you as you browse the Internet. These cookies store information about the content you are browsing, together with an identifier linked to your device or IP address.
<br/>To protect your privacy, you should be able to control how and whether cookies are accepted by your web browser. Please visit the “Help” section of your toolbar for more information about the cookies that we use and how you can prevent them from being placed. If you do not want to receive cookies, you can reject our cookies by blocking them in your Internet browser's settings or options menus. However, if you reject our cookies, you may not be able to fully experience our Platform and some of its features may not work properly. </p>
<h3 className='custom-text-primary mt-3'>UPDATING PERSONAL INFORMATION</h3>
<p>Please send an email to info@theExcelsior.in to update or modify your contact information and user preferences.</p>
<h3 className='custom-text-primary mt-3'>SECURITY STATEMENT</h3>
 <p>Excelsior has put in place various physical, electronic and managerial procedures to try to safeguard and secure the information we collect. For example, we provide strong encryptions to store certain information and have stringent managerial checks and password change policies in place. The information we collect is stored with third-party data centres that have a holistic security model with seven levels of security. Please note that the Company shall not be liable for any misuse or loss of information carried out by such third-party data centres. Furthermore, we also rely on your cell phones’ strong security model to ensure that there is no information or security leak unless intentionally processed for authentication.
<br/>We ensure that many security measures are in place to protect your online transactions, but we cannot guarantee absolute safety.</p>
<h3 className='custom-text-primary mt-3'>ADDRESS FOR PRIVACY QUESTIONS</h3>
<p>If you have questions about this policy or Excelsior’s information collection, use and disclosure practices, please contact info@theExcelsior.in. We will respond to your question or concern promptly. Please be aware that we cannot guarantee a response to questions or comments regarding topics unrelated to this policy or our privacy practices.</p>
<h3 className='custom-text-primary mt-3'>CHANGING OUR PRIVACY POLICY</h3>
<p>We may modify this Privacy Policy from time to time. Any changes to this Privacy Policy will be effective immediately upon being posted on this page. By accessing the Platform, you indicate your agreement to the modified Privacy Policy and all the changes. Please visit frequently to ensure familiarity with the most current version of this Privacy Policy.</p>
<h3 className='custom-text-primary mt-3'>MISCELLANEOUS PROVISIONS</h3>
<p>The provisions concerning our Terms of Use and the policies related to them will apply to this policy as well. </p>
</div>


    </div>
  )
}

export default PrivacPolicy