import React from 'react'
import HtmlHead from '../HtmlHead'

const Termofuse = () => {
  return (
    <div>
        <div className='container mt-4'>
        <HtmlHead
		title='Excelsior | Online Education Platform | Terms'
		desc='Best online training in Delhi NCR and Bengaluru for Data Science '
        kw='Best Data Science Course, Machine Learning Courses, Best online Course in Delhi NCR, Best online course in Bengaluru, Specialization in Data Science for Finance, Specialization in Data Science for IT, Finance Data Science, Data Science for IT, Deep Learning, Python programming, Machine Learning, Data Analytics, Financial Analytics '
			/>
				<h1 className='Banner_Heading'>EXCELSIOR</h1>
				<h3 className='mb-4 '>We don't just train, We make careers</h3>
        <h2 className='custom-text-primary mb-3'>Terms and Conditions related to our Learning Division of Excelsior.</h2>
        <h3><b>Introduction</b></h3>
        <p> Getexcelsior.com (referred to as “this site” or “our site”) and the information, services and other materials offered on this website are provided and operated by Excelsior. Infotech Pvt. Ltd. (referred to as “we”, “us” or “Excelsior.”). We offer curated and specially designed programs such as diplomas, courses, certification courses and industry-relevant programs online (“Programs”).
<br/>Platforms, Programs, and any information or Excelsior Content are provided on an “as is” and “as available” basis.

<br/>Please refer to our Terms and Conditions, Privacy Policy and other relevant documents available on the Platform (collectively referred to as the “Terms”) that govern the use of the Platform and Programs. Each Program may have a separate set of terms dealing with refunds, deferrals, payments etc. governing such Programs, which may vary from Program to Program, so please read them carefully. In addition, we do business with corporate clients who may have different contracts with us that will apply should you sign up for their services in addition to a residency program facilitated through our platform.
<br/>The following terms apply to any and all of the activities you engage in with other users on Facebook groups, Instagram pages, Facebook pages, email/SMS/phone communications, any messaging platform (Slack, Discord etc.), organized events and other social media forums who are deemed part of your business or organization. You acknowledge that certain parts of the Platform are provided by third-party service providers and that as such you will be bound by their terms and conditions. Excelsior shall not be responsible for any disruptions that occur as a result of a third-party service provider's error or failure to deliver services to you.
<br/>Please note that the use of the Platform and Programs constitutes an unconditional agreement to follow and be bound by the Terms. Although you may "bookmark" a particular portion of the Platform and thereby bypass these Terms, your use of the Platform still binds you to these Terms.
<br/>Please note that we may update these Terms from time to time without prior notice. You should review this page regularly. If we make changes, and you use our Platform or Programs after those changes are made, it will indicate that you accept the change. We recommend that you do not continue using our Platform or Programs if you are unhappy with the Terms for any reason.
</p>

<h3 className='mt-3'><b>User Conduct Policy</b></h3>
        <p> Whether you have enrolled with a program or are simply browsing, once you have accessed the platform or programs, you shall be considered a “user” for the purpose of these terms and conditions. You are responsible for all your activities in connection with the use of the platform and programs. You hereby agree to fully comply with all applicable laws, regulations, and rules in connection with such usage and that you will not resort to any unethical practices while using the platform.
<br/>Never post or transmit, or cause to be posted or transmitted, a "phishing", "pharming" or "whaling" communication anywhere on Excelsior. We take our users' security very seriously and any attempt to access a personal account will result in us taking action straight away! However, if something does happen that compromises your data, there's no chance for us to assist you in retrieving it.
<br/>You acknowledge and agree that Excelsior might sometimes need to report to the police or relevant authority if they believe it is likely that any suspicious or illegal activity has been, is being or will be carried out.
<br/>During your use of the Platform and Programs, you will:
<li>Not harass other users, students, attendees, support agents or visitors</li>
<li>Not create an atmosphere of disharmony, hostility within student groups</li>
<li>Not cheat on any homework assignment or exams for the Program</li>
<li>Not post online any secured testing materials</li>
<br/>Not share solutions to homework assignments or exams; and
<br/>Notify the instructors immediately if you become aware of any other user cheating or breaching these Terms, and comply with the requirements of the specific applicable code of conduct, if any, relating directly to a Program into which such user is enrolled.
</p>

<h3 className='mt-3'><b>User Accounts, User Registration and Delivery of Services</b></h3>
        <p> In order to participate in different Platform activities and in order to apply for a program, you will need to create an account by providing an email address and a password that is unique.
<br/>Upon payment of the Program fees – in part or whole, depending on the Program. Excelsior will grant you access to a download location where you can find information about how to use their products. Excelsior will deliver this information to you within 2 months after a successful purchase, and this shall be proof of delivery against the successful payment of fees.
<br/>You agree that you will never reveal or allow any third party access to your User Account. You also agree that you will only make and use one User Account, and that you will never have more than one User Account.
<br/>In creating your user account, you may be prompted to submit additional information, including but not limited to your name and email address. Additional information may be required to confirm that you are who you say you are. You understand and agree that all information provided by you is accurate, current, and complete and that when there is a change in this information, it will be updated accordingly.
<br/>In addition to the registration process, here at the Platform and during your use of our service or your participation in Programs with us, we may obtain certain personal data that is associated with you, us and others in connection with your use of the Platform and participation in our Programs. We may also use this information to provide you with services while you are a participant of such Programs particularly now and in the future as well as sharing it with our Educational Partners or third parties.
<br/>Access to the Programs is restricted to attendees or students who have specifically been granted access by Excelsior.
<br/>By registering your User Account, you agree that:
<li>You are registered for the Program only once and will not set up multiple User Accounts; and</li>
<li>You will abide by these Terms and any terms specific to the Program.</li>
<br/>Additional requirements apply to students and working professionals. As a student or working professional, in addition to the points above, you understand that enrolled courses are intended to provide supplemental education. You agree that it is your responsibility to complete any required coursework, if applicable.
</p>
<h3 className='mt-3'><b>Payment Terms and Refund Policy</b></h3>
        <p> Unless expressly agreed in writing by Excelsior, full payment is to be made when enrolling. In the case of Programs that include a trial window, such trial window is to be granted after the full payment has been made. During the trial window, if you decide it's not right for you, a refund can be procured after such time expires subject to our satisfaction during an inspection of your account. Once that time has passed there will be no refunds allowed for any reason.
<br/>It is the sole duty of the user enrolling in a Program to verify the veracity of the information provided and to assess the Program's applicability and relevance. A Program's enrolment is non-transferable.
<br/>You must have internet connectivity and a current valid accepted payment method as mentioned upon sign-up to make a payment for any Program or to purchase any services or products offered by Excelsior through the Platform ("Payment Method"). Excelsior does not keep any of your credit card information or any other information limited by the Reserve Bank of India (RBI) for the purpose of payment processing, and instead uses payment gateways. You agree to comply by the conditions of a third-party payment provider if you use one.
<br/>You acknowledge that if Excelsior's third-party payment provider maintains any such information, Excelsior will not be liable for its storage, and that allowing the third party to retain such information is purely at your discretion. Any loss of such information or any loss suffered by you as a result of using such information is completely your responsibility, and Excelsior is not accountable for such losses and is not responsible to reimburse or make good such losses in any way. You also agree to pay all fees associated with payments made over the Platform.
<br/>If you do not pay, your access to a Program may be revoked. The fees vary depending on where you transact with us.
<br/>If you signed up for a free trial, the trial period will last for the amount of time you indicated when you signed up. Certain additional offers may not be coupled with free trials. You are not eligible for a free trial of a paid service or product if you have subscribed to that service or product within the last six (6) months, or if your Payment Method, physical address, or email address has been associated with an account for that paid service. You may be ineligible for certain aspects of a product or service during your free trial term if you start your subscription with a free trial.
</p>
<h2 className='custom-text-primary mt-3'>Use of Programs</h2>
        <p> Excelsior maintains the right to cancel or reschedule any Program or live lectures/webinars, as well as to change, modify, or rearrange the topic schedule, as well as the point value or weight of assignments, tests, quizzes, examinations, projects, and other similar progress evaluations. You also understand that Excelsior reserves the right to limit, suspend, or terminate your use of the Platform or Programs, as well as any Excelsior-provided services related to the Programs, such as access to Excelsior coaches or support services, evaluation services, or certifications, at any time and for any reason. You also accept that Excelsior reserves the right to change or discontinue any and all services associated to its Programs at any time.
<br/>You agree that Excelsior will not be liable to you or any other person as a result of any such change, suspension, or discontinuation. Nothing in these Terms obligates Excelsior to support or maintain the Platform or Programs, or any component or portion thereof, or any connected services.
<br/>If you no longer wish to participate in any Program, you may do so by giving Excelsior notice.
<br/>Excelsior online live lectures and webinars participants will receive email access to these classes. You agree not to give this access to anybody else. If you are unable to attend an online live lecture/webinar, please let us know as soon as possible.
<br/>You are solely responsible for obtaining and maintaining any hardware, software, and other internet, wireless, broadband, phone, or other mobile communication device connection services required to connect to, access, receive, or use the Platform, including, without limitation, hardware devices, software, and other internet, wireless, broadband, phone, or other mobile communication device connection services. You are solely responsible for ensuring that such equipment or auxiliary services are compatible with the Platform, and you are solely responsible for all charges incurred in connection with the Platform and Program in relation to all such equipment and supplementary services.
</p>
<h2 className='custom-text-primary mt-3'>Educational Partners and Accreditation</h2>
        <p> Excelsior is an education service provider, not a university, that offers programmes in collaboration with Indian and international universities, educational institutions, governmental bodies, non-governmental organisations, corporations, and other organisations (each a "Educational Partner").
<br/>Admission to an Educational Partner's degree/diploma programmes is distinct from acceptance into and/or participation in one or more Programs. You agree and acknowledge that nothing in these Terms or elsewhere with respect to your use of the Platform or any Program (a) enrols or registers you in an Educational Partner, or any other school, division, institute, or programme of or associated with an Educational Partner, and (b) allows you to access or use the resources of any Educational Partner, or to receive any benefits or privileges of any Educational Partner, other than the Programs.
<br/>Excelsior may award a certification or other kind of recognition to participants who have demonstrated satisfactory mastery of the Program material. Excelsior will have sole discretion over whether or not to provide any such credential acknowledgement to a specific participant. For some Programs, we may choose not to provide any certification or other acknowledgement. Excelsior may decide whether or not to offer a record of a participant's participation in a Program at its own discretion. Excelsior will establish the format of any credential or other acknowledgement, as well as any performance, issued by Excelsior in relation to Programs at its exclusive discretion, which may vary from Program to Program.
<br/>After meeting the criteria and objectives of Excelsior and its Educational Partners, you will be issued a certificate of successful completion of a Program ("Program Certificate"). You accept that any Program Certificate given may not be linked with any Educational Partner and may not be used to replace or communicate academic credit or certification for any Educational Partner.
<br/>Taking a Program will not earn you academic credit from Excelsior or any other Educational Partner. If you are taking a Program for academic credit or certification as a student of, or otherwise through, an Educational Partner, any such credit or certification may only be awarded directly by the Educational Partner based on its own policies and procedures, and you may be required by that Educational Partner to be registered or enrolled with the Educational Partner in order to receive credit or certification; and, in any event, Excelsior will have no authority or responsibility for any such credit or certification.
<br/>You understand and agree that, in addition to Excelsior's Terms, any Program linked with an Educational Partner may be subject to the Educational Partner's terms, policies, and procedures. Without limiting the foregoing, if you are a student registered or enrolled at, or otherwise attending, an Educational Partner and are taking a Program for credit or certification through that Educational Partner, you acknowledge and agree that (a) the Educational Partner may have its own terms, policies, or procedures regarding your eligibility to participate in the Program, your participation in the Program, the requirements or prerequisites for receiving credit or certification through that Educational Partner; (b) the Educational Partner may have its own terms, policies, or procedures regarding your eligibility
</p>

<h2 className='custom-text-primary mt-3'>Excelsior Intellectual Property Rights</h2>
        <p> Text, software, scripts, graphics, maps, photos, sounds, music, videos, logos, offers, advertisements, interactive features, and other materials are all examples of "content," which includes but is not limited to text, software, scripts, graphics, maps, photos, sounds, music, videos, logos, offers, advertisements, interactive features, and other materials.
<br/>Excelsior and its licensors own and manage the Platform, Programs, and related services. All content, including but not limited to online/live lectures, speeches, video lessons, quizzes, presentation materials, homework assignments, programming assignments, programmes, code, and other images, text, layouts, arrangements, displays, illustrations, documents, materials, audio and video clips, HTML and files (collectively "Excelsior Content"), is the property of Excelsior and/or its affiliates or partners. Excelsior owns all of the software on the Platform, which is protected by Indian and international copyright laws.
<br/>Excelsior may award a certification or other kind of recognition to participants who have demonstrated satisfactory mastery of the Program material. Excelsior will have sole discretion over whether or not to provide any such credential acknowledgement to a specific participant. For some Programs, we may choose not to provide any certification or other acknowledgement. Excelsior may decide whether or not to offer a record of a participant's participation in a Program at its own discretion. Excelsior will establish the format of any credential or other acknowledgement, as well as any performance, issued by Excelsior in relation to Programs at its exclusive discretion, which may vary from Program to Program.
<br/>The Excelsior logos, trademarks, and service marks that may appear on the Platform and in the Program ("Excelsior Marks") are Excelsior's property and are protected by Indian and foreign law. All other trademarks, service marks, and logos used with or without attribution on the Platforms, Online Courses, or Programs are the trademarks, service marks, or logos of their respective owners. Furthermore, aspects of the Platforms are protected by trade dress and other Indian and international intellectual property laws, and may not be copied, reproduced, downloaded, or disseminated in any way without Excelsior's express written approval in whole or in part.
<br/>You agree not to (a) reproduce, duplicate, copy, sell, resell or exploit for any commercial purpose any Excelsior Content or any portion of it, other than as expressly allowed under these Terms; and (b) use the Excelsior Marks or the name, trademarks, service marks, or other materials of any Educational Partner in connection with, or to transmit, any unsolicited communications or emails or for a commercial purpose any Excelsior Content or any portion of it, other than as expressly.
<br/>Please double-check every content before using it. Please contact us immediately if you come across any Content that is erroneous, infringing, offensive, indecent, or objectionable at the address shown at the bottom of this page.
</p>

<h2 className='custom-text-primary mt-3'>Third-Party Intellectual Property</h2>
        <p> Excelsior values third-party intellectual property rights and actively promotes the preservation of all third-party intellectual property, including copyrights and trademarks (collectively referred to as "IP"). It is our policy to respond quickly to unambiguous notices of alleged intellectual property violation. If we receive proper notification of IP infringement, we will remove or disable access to the material claimed to be the subject of infringing activity as part of our response.
<br/>Excelsior will not be held liable for any unauthorised use of third-party IP, and any user who does so or infringes on any IP available on the Platform will fully indemnify and hold Excelsior blameless from any and all claims that may arise as a result of such use.
<br/>Please give us with the following information if you believe your product or other work has been misrepresented or exploited in a way that constitutes copyright infringement, or if your intellectual property rights have been violated in any other way.
<br/>An electronic or physical signature of a person authorised to act on behalf of the product's owner, copyright holder, or other intellectual property owner. A description of the product, work, or other intellectual property you believe has been misrepresented or infringed upon. A description of the item on the Platform/Program that you think is misrepresenting or violating your product, work, or other intellectual property.
<br/>A statement from you stating you have a good faith conviction that the disputed use is not authorised by the product, work, copyright, or intellectual property owner, or its agent, or by applicable law; and
<br/>A declaration by you, made under penalty of perjury, that the information in your notification is correct and that you are the product, work, copyright, or intellectual property owner or entitled to act on behalf of such owner.
</p>

<h2 className='custom-text-primary mt-3'>Limited License</h2>
        <p> Excelsior values third-party intellectual property rights and actively promotes the preservation of all third-party intellectual property, including copyrights and trademarks (collectively referred to as "IP"). It is our policy to respond quickly to unambiguous notices of alleged intellectual property violation. If we receive proper notification of IP infringement, we will remove or disable access to the material claimed to be the subject of infringing activity as part of our response.
<br/>Despite the preceding, you may be provided with access to some reference papers, digital textbooks, and articles with the authorization of third parties, and your use of that information is subject to certain restrictions and conditions, which you agree to follow. You are not permitted to reverse-engineer, decompile, disassemble, or otherwise gain access to the source code of any software utilised to operate the Platform or the Programs. Excelsior may include software, code, instructions, or other similar information in the Excelsior Content for the Programs from time to time; any such information is provided "as-is" for educational purposes only and is subject to the 'Disclaimer' and 'Limitation of Liability' sections below, as well as other terms herein. It is totally forbidden to exploit such information for commercial purposes. All rights not expressly granted herein to the Platforms, Excelsior Content, and Excelsior Marks are reserved by Excelsior and/or its affiliates and licensors.
<br/>The sale or rental of I any part of the Excelsior Content, (ii) any derivative works based in part on the Excelsior Content, or (iii) any collective work containing any part of the Excelsior Content. The selling of access to any portion of the Excelsior Content or a link to any part of the Excelsior Content; in exchange for a charge, providing training, support, or editorial services that utilise or reference the Excelsior Content. The use of Excelsior Content for tuition-based instruction by a college, university, school, or other educational institution, The use of Excelsior Content for internal professional development or training by a for-profit or non-profit organisation; and The use of Excelsior Content for display, upload, or making available in any manner to the general public, including but not limited to social media sites, video download sites, and torrents.
<br/>In exchange for a charge, providing training, support, or editorial services that utilise or reference the Excelsior Content. The use of Excelsior Content for tuition-based instruction by a college, university, school, or other educational institution, The use of Excelsior Content for internal professional development or training by a for-profit or non-profit organisation; and The use of Excelsior Content for display, upload, or making available in any manner to the general public, including but not limited to social media sites, video download sites, and torrents.
</p>
<h2 className='custom-text-primary mt-3'>User Content</h2>
        <p> The Platform may allow you to upload forum posts, chat with other users and Excelsior's counsellors, user discussions, profile pages, and other social media content and media, as well as certain information and materials for use with the Programs, such as questions, hypotheticals, examples, assignments, industry projects, and so on (collectively "User Content"). Excelsior has no claim to any User Content you submit or make accessible for use on the Platform or through the Programs. As a result, the user will be the only and exclusive owner of all rights, title, and interest in and to the User Content, subject to the licence granted to Excelsior above.
<br/>You hereby grant Excelsior an irrevocable, worldwide, perpetual, royalty-free and non-exclusive licence to use, distribute, reproduce, modify, adapt, publicly perform and publicly display any User Content you submit via the Platform or Programs or otherwise make available to Excelsior, with the right to sublicense such rights (to multiple tiers), for any p (including for any commercial purpose). Excelsior maintains the right, at any time and for any reason, to delete any User Content.
<br/>To the extent that you provide any User Content, you represent and warrant that (a) you have all necessary rights, licences, and/or clearances to provide such User Content and permit Excelsior to use such User Content as provided above, (b) such User Content is accurate and reasonably complete, (c) you will be responsible for any third-party fees related to the provision and use of such User Content as between you and Excelsior, and (d) such User Content complies with all applicable laws and regulations.
<br/>Excelsior has no control over the User Content submitted on the Platform, such as messages, reviews, or comments, and cannot guarantee its correctness, integrity, or quality. Excelsior will not be liable in any way for any User Content, including any errors or omissions, or any loss, damage, or defamation of any kind resulting from your publishing or use of any User Content. You are responsible for adhering to any applicable laws regarding User Content.
<br/>It is forbidden for you to post the following Content on the Platform.
<li>Content that is defamatory, obscene, or libellous, or that harasses, discriminates, damages, or threatens others;</li>
<li>Content that encourages people to engage in unlawful crimes with the goal of committing them;</li>
<li>Content that encourages people to engage in unlawful crimes with the goal of committing them;</li>
<li>Infringing or misappropriating third-party patents, trademarks, trade secrets, right of publicity, or other intellectual property rights;</li>
<li>Content that you don't have permission to share;</li>
<li>Advertising or any sort of commercial solicitation; Profane, pornographic, obscene, indecent, or unlawful content;</li>
<li>Content relating to political partisanship;</li>
<li>Content that provides purposefully false information or is posted with the intent to deceive others;</li>
<li>Viruses, Trojan horses, worms, time bombs, cancelbots, or other disabling devices or other harmful components that are intended to or may damage, adversely interfere with, secretly intercept, or expropriate any system, data, or personal information;</li>
<li>Any high-volume, automated, or electronic method of accessing the Platform (including, but not limited to, robots, spiders, or scripts);</li>
<li>Content that infringes on the rights of other Platform users; or</li>
<li>Content that breaks any applicable local, state, national, or international law, or advocates or encourages unlawful action in any way.</li>
</p>

<h2 className='custom-text-primary mt-3'>Platform Security</h2>
<p>You are prohibited from violating or attempting to violate the security of the Platform or any other Excelsior associate Platform, including, without limitation, <li>Accessing data not intended for such user or logging onto a server or account that the user is not authorised to access;</li> <li> attempting to probe, scan, or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization;</li> <li> attempting to interfer with the Platform or any other Excelsior associate Platform</li>
<li>Forging any TCP/IP packet header or any part of the header information in any email or newsgroup posting; or </li><li> Sending unsolicited emails, including marketing and/or advertising of products or services." System or network security violations may result in legal or criminal responsibility. Excelsior will investigate possible violations and may involve and cooperate with law enforcement agencies in punishing users who are implicated in such crimes. You agree not to use any device, software, or routine to disrupt or attempt to disrupt the Platform's normal operation or any activity taking place on it.</li>
<br/>You also agree not to use or attempt to use any engine, software, tool, agent, or other device or mechanism (including, without limitation, browsers, spiders, robots, avatars, or intelligent agents) to navigate or search the Platform other than the Excelsior-provided search engine and search agents and generally available third-party web browsers (e.g., Google Chrome or Microsoft Explorer). 
</p>
<h2 className='custom-text-primary mt-3'>Limitation of Liability</h2>
<p>Neither Excelsior nor any of its Educational Partners, affiliates, employees, directors, officers, agents, vendors, or suppliers shall be liable to you or any other person for any indirect, special, incidental, or consequential losses or damages of any kind arising out of or in connection with the use or inability to use this Platform or Programs, including, without limitation, damages for lost profits, loss of go. Excelsior will not be liable for any losses in excess of $1,000 or, in the case of enrolled students, the fees paid in connection with their registration into a Program.</p>
<h2 className='custom-text-primary mt-3'>Site Linking</h2>
<p>The Platform may include connections to pages on other websites (referred to as "Linked Sites"), which may contain Content or sell items and/or services. These Linked Sites are not created, edited, controlled, or monitored by Excelsior. You acknowledge and agree that (a) we are not responsible for the accuracy or availability of information provided by Linked Sites; (b) we have no control over or endorsement of the sponsors of such Linked Sites, or the content, products, advertising, or other materials presented on such Linked Sites; and (c) you agree to the Linked Sites' terms and conditions. We reserve the right to remove any Linked Sites from the Platform at any time, for any reason.
<br/>Excelsior IS NOT RESPONSIBLE FOR ANY TRANSACTIONS YOU HAVE WITH THIRD PARTIES THROUGH THE LINKED SITES, OR FOR ANY LIABILITY ARISING FROM REPRESENTATIONS OR INFORMATION PROVIDED ON SUCH LINKED SITES.
<br/>We recognise that Linked Sites may contain content that is protected by intellectual property rights owned by the Linked Sites' operator. We respect such rights and present the links solely as a resource. The fact that we have provided connections to any Linked Site in no way implies or creates any kind of relationship or collaboration with the Linked Site's operator.
<br/>Without our prior written consent, you may not link to our Platform from any other website, application, intranet, or extranet site. If you want to create links, please get in touch with us first. You must not suggest in any manner, directly or by implication, that you have obtained the endorsement, sponsorship, or support of Excelsior, including its Educational Partners, employees, agents, directors, officers, or shareholders, in establishing links.</p>
<h2 className='custom-text-primary mt-3'>Indemnity</h2>
<p>You agree to hold Excelsior and its Educational Partners harmless from any and all claims, liabilities, damages, losses, and expenses, including reasonable attorneys' fees and costs, relating to or arising out of (a) your use or attempted use of the Platforms or Programs in violation of the Terms; (b) your violation of any law or right of a third party; or (c) information or Content that you or others post or otherwise make available on the Platform or the Programs.</p>
<h2 className='custom-text-primary mt-3'>Termination of Rights</h2>
<p>You agree that Excelsior may deactivate your account or otherwise terminate your use of the Platform or enrollment in a Program at any time, for any reason, including, without limitation, if Excelsior believes that you have <li>Breached the Terms; </li><li>infringed on a third party's intellectual property rights; (c) posted, uploaded, or transmitted unauthorised Content on the Platform; or </li><li>Violated or acted inconsistently with the letter or spirit of the Terms</li>
<br/>You agree that Excelsior may deactivate or terminate your access to the Platforms or Programs at any time without notice to you, and that Excelsior will not be liable to you or any third party if your account or enrollment in a Program is terminated. You also acknowledge that Excelsior may keep and preserve your information on its systems even if your account or enrollment in the Programs is terminated.</p>
<h2 className='custom-text-primary mt-3'>Miscellaneous Provisions</h2>
<p>You declare that you are 18 years of age or older by accepting the Terms through your usage of the Platform. You may use the Platform only under the supervision of a parent or legal guardian who agrees to be bound by the Terms if you are under the age of 18 or the legal age in your jurisdiction to enter into a binding contract. If you are a parent or legal guardian agreeing to the Terms on behalf of a child under the age of 18, please be aware that you are solely responsible for his or her use of the Platform, including any financial charges and legal liability that may arise. 
<br/>You represent and warrant that you have the right, authority, and capacity to engage into the Terms and to abide by all of the terms and conditions set out herein by using the Platform. Individuals under the age of 18 are not permitted to utilise the Programs.
<br/>Under these Terms and any Program-specific terms, Excelsior may freely transfer or assign any portion of its rights or delegate its duties. Without Excelsior's prior written agreement, you may not transfer or assign any portion of your rights or delegate your obligations under these Terms or any Program-specific terms, whether by operation of law or otherwise.
<br/>These Terms, as well as any Program-specific terms disclosed with you, will be governed by, construed, and enforced in accordance with Indian laws, as they apply to agreements entered into and to be performed solely within India, without regard to conflict of laws principles. You agree that any legal action taken by Excelsior, you, or any third party to enforce these Terms or any Program-specific terms disclosed with you, or in connection with any matters relating to the Platform or Programs, would be brought exclusively in Mumbai's courts. When a disagreement emerges, the parties must use all reasonable attempts to resolve the disagreement through good faith negotiations
<br/>If the parties are unable to resolve any dispute or claim amicably, any dispute or claim arising out of or in connection with the Terms or any Program-specific terms shared with you, including any question regarding its existence, validity, or termination, will be referred to arbitration under the Arbitration and Conciliation Act, 1956, as amended ("Act") before a sole arbitrator to be appointed by Excelsior. The hearings will be conducted in English, and the arbitration will take place in Mumbai.
<br/>If any provision of the Terms or any Program-specific terms shared with you is found to be unlawful, void, or unenforceable for any reason, that provision shall be deemed severable from the other provisions herein, and the validity and enforceability of the remaining provisions shall not be affected. Excelsior shall have no liability under these Terms or any Program-specific terms shared with you if Excelsior fails to perform any of its obligations under these Terms or any Program-specific terms shared with you as a result of any fire, flood, earthquakes, other acts of God, war, civil unrest, terrorism, Internet failures, governmental act or court order, national emergency, strikes or labour disputes, or any other event beyond Excelsior's control
<br/>Excelsior will not be liable for any damage or other issues resulting from any unauthorised changes to these Terms made by hacking or cracking this page.
<br/>Excelsior's omission to assert or enforce any right or provision of the Terms, including any Program-specific terms discussed with you, shall not be construed as a waiver of that right or provision. If a court of competent jurisdiction finds any provision of the Terms or any Program-specific terms shared with you to be invalid, the parties agree that the court should endeavour to give effect to the parties' intentions as reflected in the provision, to the extent that this is lawfully possible, and the other provisions of the Terms or any Program-specific terms shared with you.
<br/>These Terms, as well as any Program-specific terms shared with you, represent the entire agreement between you and Excelsior regarding the matters set forth herein, and may not be modified except in writing, as posted on the Platforms by Excelsior, or through a specific writing between you and Excelsior.
<br/>Under the Agreements or any Program-specific terms agreed with you, Excelsior may freely transfer or assign any portion of its rights or delegate its duties. Without Excelsior's prior written consent, you may not transfer or assign any portion of your rights or delegate your obligations under the Terms or any Program-specific terms shared with you, whether by operation of law or otherwise, and any such attempted transfer or assignment shall be null and void.
<br/>This document is an electronic record under the Information Technology Act of 2000 and its Rules, as well as the revised provisions of different legislation dealing to electronic records as changed by the Information Technology Act of 2000. This electronic record is created by a computer system and does not require physical or electronic signatures.
<br/>Any notice or communication needed to be made to Excelsior under these Terms or any Program-specific terms communicated with you may be sent to the following addresses by writing or email. </p>

			</div>
    </div>
  )
}

export default Termofuse